storing details in db api
Nexus-Optima/Backend-Engine pull request #5
Opened 2024-03-19 10:57 UTC by Anikkk

2024-03-21 07:28 UTC, kaivan-s commented on src/app.py
> +    print(data)
Remove this statement. Instead add a log.

2024-03-21 07:29 UTC, kaivan-s commented on src/app.py
> +    success, error_message = update_client_details(table, userid, username,email, phone, company)
This entire logic should be somewhere else, the main function of this method is to call the update_client_details method. 
Logic should be in that file itself. 

Keep the main file clean.

2024-03-21 07:30 UTC, kaivan-s requested changes
Added a few comments. Please check

2024-03-23 04:50 UTC, Anikkk commented on src/app.py
> +    success, error_message = update_client_details(table, userid, username,email, phone, company)
the entire logic has been implemented in user details.py file
![Screenshot 2024-03-23 101933](https://github.com/Nexus-Optima/Backend-Engine/assets/43331966/05b5d85d-ca8e-4ac2-8f63-96fea3726078)

2024-03-23 04:50 UTC, Anikkk commented on src/app.py
> +    print(data)
done

2024-03-26 10:00 UTC, kaivan-s commented on src/Database/user_details.py
> +        print(items)
Remove this.

2024-03-26 10:05 UTC, kaivan-s requested changes
Looks Good. Just remove a print statement and it should be fine.

2024-03-26 10:17 UTC, Anikkk commented on src/Database/user_details.py
> +        print(items)
done

2024-03-26 10:19 UTC, kaivan-s approved these changes

2024-03-26 10:26 UTC, merged